// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TradingIQ

//@version=5

// @description used to calculate various ICT related price levels and strategies. An ongoing project. 

library("ICTlibrary", dynamic_requests = true)

// Thank you PineCoders!!
import PineCoders/Time/4 as pct


// @type UDT for FVG calcualtions
// @field H high price of user-selected timeframe 
// @field L low price of user-selected timeframe 
// @field direction  FVG direction => "Up" or "Down"
// @field T => time of bar on user-selected timeframe where FVG was created
// @field fvgLabel optional label for FVG
// @field fvgLineTop optional line for top of FVG
// @field fvgLineBot optional line for bottom of FVG
// @field fvgBox     optional box for FVG

export type FVG 

    float  H 
    float  L 
    string direction 
    int    T
    label  fvgLabel
    line   fvgLineTop 
    line   fvgLineBot
    box    fvgBox 
    
// @type quickly pair a line and label together as UDT
// @field lin Line you wish to pair with label
// @field lab Label you wish to pair with line

export type labelLine 

    line  lin 
    label lab 

// @type UDT for order block calculations
// @field orderBlockData array containing order block x and y points   
// @field orderBlockBox   optional order block box
// @field vioCount = 0    violation count of the order block. 0 = Order Block, 1 = Breaker Block
// @field bool        traded = false  False = OB hasn't been traded. True = OB has been traded. This is to limit the number of trades at the order block.
// @field status = "OB"   status == "OB" => Level is order block. status == "BB" => Level is breaker block.
// @field orderBlockLab   options label for the order block / breaker block.

export type orderBlock

    array<float> orderBlockData
    box    orderBlockBox
    int    vioCount = 0
    bool   traded = false
    string status = "OB"
    label  orderBlockLab

// @type UDT for strong highs and strong lows
// @field price             price of the strong high or strong low 
// @field timeAtprice       time of the strong high or strong low
// @field strongPointLabel  optional label for strong point         
// @field strongPointLine   optional line for strong point              
// @field overlayLine       optional lines for strong point to enhance visibility     
// @field overlayLine2      optional lines for strong point to enhance visibility             


export type strongPoints 

    float price 
    int   timeAtprice
    label strongPointLabel
    line  strongPointLine
    line  overlayLine
    line  overlayLine2

// @type UDT for dispacements
// @field highPrice        high price of displacement         
// @field lowPrice         low price of displacement 
// @field timeAtPrice      time of bar where displacement occurred      
// @field displacementBox  optional box to draw displacement
// @field displacementLab  optional label for displacement  

export type displacement 


    float highPrice 
    float lowPrice
    int   timeAtPrice
    box   displacementBox
    label displacementLab

// @type UDT for po3 calculations
// @field dHigh           higher timeframe high price                  
// @field dLow            higher timeframe low price                  
// @field dOpen           higher timeframe open price                                                        
// @field dClose          higher timeframe close price           
// @field po3box          box to draw po3 candle body         
// @field po3line         line array to draw po3 wicks        
// @field po3Labels       label array to label price points of po3 candle             

export type po3data 


    float        dHigh 
    float        dLow 
    float        dOpen 
    float        dClose
    box          po3box 
    array<line>  po3line
    array<label> po3Labels


// @type UDT for session macros
// @field sessions      Array of sessions, you can populate this array using the "quickTime" function located above "export macros".
// this array holds "true" at index if session is active, "false" is not. 
// @field prices        Matrix of session data -> open, high, low, close, time
// @field sessionTimes  Array of session names. Pairs with array<bool> sessions.         
// @field sessionLines  Optional array for sesion drawings.

export type macros 


    array  <bool>   sessions
    matrix <float>  prices
    array  <string> sessionTimes
    matrix <line>   sessionLines

// @type UDT for data storage and drawings associated with OTE strategy
// @field upTimes  time of highest point before trade is taken                             
// @field dnTimes  time of lowest point before trade is taken         
// @field tpLineLong      line to mark tp level long    
// @field tpLabelLong     label to mark tp level long   
// @field slLineLong      line to mark sl level  long
// @field slLabelLong     label to mark sl level long
// @field tpLineShort     line to mark tp level short         
// @field tpLabelShort    label to mark tp level short          
// @field slLineShort     line to mark sl level  short      
// @field slLabelShort    label to mark sl level short     
    
export type OTEtimes 


    array<int>   upTimes 
    array<int>   dnTimes 

    line  tpLineLong 
    label tpLabelLong 
    line  slLineLong 
    label slLabelLong 

    line  tpLineShort 
    label tpLabelShort 
    line  slLineShort 
    label slLabelShort 
   
// @type UDT for data storage and drawings associated with liquidity sweeps
// @field upSweeps matrix containing liquidity sweep price points and time points for up sweeps 
// @field dnSweeps matrix containing liquidity sweep price points and time points for down sweeps          
// @field upSweepDrawings  optional up sweep box array. Pair the size of this array with the rows or columns, 
// 											however you structure the above matricies, to associate the box created at each index 
// 											with the identified up liquidity sweep.     
// @field dnSweepDrawings  optional up sweep box array. Pair the size of this array with the rows or columns, 
// 											however you structure the above matricies, to associate the box created at each index 
// 											with the identified down liquidity sweep.       
 
export type sweeps 

    matrix<float> upSweeps
    matrix<float> dnSweeps
    array<box>    upSweepDrawings 
    array<box>    dnSweepDrawings



// @type UDT for drawings associated with the Liquidity Raid Strategy
// @field tpLine  tp line for the liquidity raid entry   
// @field tpLabel tp label for the liquidity raid entry      
// @field slLine  sl line for the liquidity raid entry     
// @field slLabel sl label for the liquidity raid entry   

export type raidExitDrawings 

    line  tpLine 
    label tpLabel 
    line  slLine 
    label slLabel 

// @type UDT for data storage and drawings associated with the Model 2022 Strategy
// @field mTime               time of the FVG where entry limit order is placed        
// @field mIndex              array index of FVG where entry limit order is placed. This requires an array of FVG data, which is defined above.             
// @field mEntryDistance    the distance of the FVG to the 50% range. M2022 looks for the fvg closest to 50% mark of range.                              
// @field mEntry            the entry price for the most eligible fvg            
// @field fvgHigh           the high point of the eligible fvg              
// @field fvgLow            the low point of the eligible fvg     
// @field longFVGentryBox     long FVG box, used to draw the eligible FVG                           
// @field shortFVGentryBox    short FVG box, used to draw the eligible FVG                    
// @field line50P            line used to mark 50% of the range       
// @field line100P           line used to mark 100% (top) of the range                                
// @field line0P             line used to mark 0% (bottom) of the range        
// @field label50P          label used to mark 50% of the range                                
// @field label100P         label used to mark 100% (top) of the range                                           
// @field label0P           label used to mark 0% (bottom) of the range                       
// @field array <float> sweepData an array containing price points of the liquidity sweep that sets up the model 2022 entry                           

export type m2022 

    int           mTime 
    int           mIndex
    float         mEntryDistance
    float         mEntry
    float         fvgHigh 
    float         fvgLow
    box           longFVGentryBox 
    box           shortFVGentryBox 
    line          line50P
    line          line100P 
    line          line0P
    label         label50P
    label         label100P 
    label         label0P
    array <float> sweepData

// @type UDT for data storage and drawings associated with the Silver Bullet Strategy
// @field bool    session              whether the eligible session for silver bullet is active, true == session active, false = inactive                
// @field sessionStr           name of the session for silver bullet
// @field sessionHigh = high   high of session // use math.max(silverBullet.sessionHigh, high)     
// @field sessionLow  = low    low of session  // use math.min(silverBullet.sessionLow, low)                    
// @field sessionFVG           if applicable, the FVG created during the session          
// @field sessionFVGdraw       if applicable, draw the FVG created during the session     
// @field bool    traded      = false  whether the current session has been traded                                                  
// @field tp                   tp of trade entered at the session FVG                       
// @field sl                   sl of trade entered at the session FVG          
// @field sessionDraw          optional draw session with box          
// @field sessionDrawLabel     optional label session with label              

export type silverBullet 


    bool    session 
    string  sessionStr
    string  sessionBias
    float   sessionHigh = high
    float   sessionLow  = low 
    float   sessionFVG
    box     sessionFVGdraw
    bool    traded      = false 
    float   tp 
    float   sl
    box     sessionDraw
    label   sessionDrawLabel

// @type UDT for trade exit drawings associated with the Silver Bullet Strategy
// @field tpLine  tp line drawing for strategy
// @field tpLabel tp label drawing for strategy
// @field slLine  sl line drawing for strategy
// @field slLabel sl label drawing for strategy 
 
export type silverBulletDrawings 


    line  tpLine 
    label tpLabel 
    line  slLine
    label slLabel


// @type UDT for data storage and drawings associated with the Unicorn Model Strategy
// @field chart.point hPoint  the most recent chart point of the Unicorn Model setup, this is used to draw a polyline showing the setup
// @field chart.point hPoint2 the second most recent chart point of the Unicorn Model setup, this is used to draw a polyline showing the setup          
// @field chart.point hPoint3 the third most recent chart point of the Unicorn Model setup, this is used to draw a polyline showing the setup              
// @field breakerBlock used to draw the breaker block required for the Unicorn Model        
// @field FVG          used to draw the FVG required for the Unicorn model          
// @field topBlock   price of top of breaker block, can be used to detail trade entry          
// @field botBlock   price of bottom of breaker block, can be used to detail trade entry  
// @field startBlock start time of the breaker block, used to set the "left = " param for the box 
// @field includes  used to store the time of the breaker block, or FVG, or the chart point sequence that setup the Unicorn Model.
									// you can reference the data in this array with the ".includes()" function to ensure trades are not entered 
									// more than 1 time at each Unicorn setup                   
// @field entry            // eligible entry price, for longs"math.max(topBlock, FVG.get_top())", 
// 															 for shorts"math.min(botBlock, FVG.get_bottm())"   
// @field tpLine  optional line to mark PT   
// @field tpLabel optional label to mark PT             
// @field slLine  optional line to mark SL          
// @field slLabel optional label to mark SL   

export type unicornModel 

    chart.point hPoint 
    chart.point hPoint2 
    chart.point hPoint3
    box breakerBlock 
    box FVG 
    float topBlock 
    float botBlock 
    int   startBlock 
    array<int> includes
    float entry 
    line tpLine 
    label tpLabel 
    line slLine 
    label slLabel

// @type UDT for data storage and drawings associated with rejection blocks
// @field chart.point rejectionPoint chart point (time / price) of rejection, should be swing high or low
// @field bodyPrice      candle body price closest to the rejection point, for "Up" rejections => math.max(open, close),
//									  "Down"  => math.min(open, close), this determines the length of the wick 
// @field rejectionBox   optional box drawing of the rejection block           
// @field rejectionLabel optional label for the rejection block

export type rejectionBlocks 

    chart.point rejectionPoint 
    float       bodyPrice 
    box         rejectionBox 
    label       rejectionLabel 
    
// @type UDT for data storage and drawings associated with equal highs / equal lows
// @field connector     single line placed at the first high or low, y = avgerage of distinguished equal highs/lows
// @field connectorLab  optional label to be placed at the highs or lows      
// @field levels        array containing the equal highs or lows prices        
// @field times         array containing the equal highs or lows individual times    
// @field startTime     the time of the first high or low that forms a sequence of equal highs or lows                              
// @field radiate       options label to "radiate" the label in connector lab. Can be used for anything      

export type equalLevelsDraw


    line         connector 
    label        connectorLab
    array<float> levels 
    array<int>   times
    int          startTime
    array<label> radiate



// @type UDT for data storage of historical price points. 
// @field highArr        array containing historical high points        
// @field lowArr         array containing historical low points         
// @field timeArr        array containing historical time points       
// @field logArr         array containing historical log returns      
// @field signArr        array containing historical price directions             
// @field closeArr       array containing historical close points         
// @field binaryTimeArr  array containing historical time points, uses "push" instead of "unshift" to allow for binary search            
// @field binaryCloseArr array containing historical close points, uses "push" instead of "unshift" to allow the correct
// 										  index to be accessed when "binaryTimeArr" is binary searched
// @field binaryOpenArr  array containing historical optn points, uses "push" instead of "unshift" to allow the correct
// 										  index to be accessed when "binaryTimeArr" is binary searched  
// @field atrTFarr       array containing historical user-selected TF atr points                  
// @field openArr        array containing historical open points          

export type necessaryData

    array<float> highArr
    array<float> lowArr
    array<int>   timeArr
    array<float> logArr 
    array<float> signArr 
    array<float> closeArr 
    array<int>   binaryTimeArr 
    array<float> binaryCloseArr 
    array<float> binaryOpenArr
    array<float> atrTFarr 
    array<float> openArr

// @enum enum for user selection of Unicorn Model Trade Exits
// @field sL    swing low exit, whether for profit (short) or loss (long)         	
// @field sH    swing high exit, whether for profit (long) or loss (short)                   
// @field bFVG  long entry stop loss of math.min(FVGbottom/BBbottom)                     
// @field tFVG  short entry stop loss of math.max(FVGtop/BBtop)                       
// @field zero5 fib TP of -0.5            
// @field one5  fib TP of -1                
// @field two5  fib TP of -2          

export enum unicornExits 


    sL    = "Swing Low"
    sH    = "Swing High"
    bFVG  = "FVG/BB Bottom"
    tFVG  = "FVG/BB Top"
    zero5 = "Fib -0.5"
    one5  = "Fib -1"
    two5  = "Fib -2"

// @enum enum for trade exit drawings associated with the Silver Bullet Strategy
// @field pdH this setting forces the silver bullet strategy to exit at the pd High, whether as PT or SL   
// @field pdL this setting forces the silver bullet strategy to exit at the pd Low , whether as PT or SL          
// @field sH  this setting forces the silver bullet strategy to exit at a recent swing High, whether as PT or SL     
// @field sL  this setting forces the silver bullet strategy to exit at a recent swing Low , whether as PT or SL         

export enum silverBulletLevels 


    pdH = "Previous Day High"
    pdL = "Previous Day Low"
    sH  = "Swing High"
    sL  = "Swing Low"

// @enum used for classifying key prices and times for the liquidity raid strategy and associated drawings    
// @field CB     closest breaker block for entry 
// @field CBB    the bottom price of the breaker block
// @field CBS    the start time of the breakerblock
// @field CBT    the top price of the breaker block
// @field HR     if session high was raided, 1 => true 
// @field LR     if session low was raided, 1 => true 
// @field ST     start time of pattern, which is the end of session price
// @field SP     start price of pattern, which is the end of session time
// @field H      session high price
// @field L      session low price 
// @field ET     end time of pattern
// @field EP     end price of pattern
// @field HRT    time of session high
// @field HRP    price of highest high that "raided" the session high 
// @field HRVT   time of highest high that raided the session high
// @field LPRHR  lowest price reached during the high raid
// @field LPRHRT time of the lowest price reached during the high raid
// @field LRT    time of the session low
// @field LRP    price of the lowest low that raided the session low
// @field LRVT   time of the lowest low that raided the session low
// @field HPRLR  high price reached during the low raid
// @field HPRLRT time of the highest price rached during the low raid
// @field LTP    Long TP price
// @field LTPT   Long TP Time
// @field LSL    Long SL price
// @field LSLT   Long SL Time
// @field STP    Short TP price
// @field STPT   Short TP Time
// @field SSL    Short SL time
// @field SSLT   Short SL Time

export enum raidCoordinates

    CB     = "Closest Breaker"
    CBB    = "Closest Breaker Bottom"
    CBS    = "Closest Breaker Start"
    CBT    = "Closest Breaker Top"
    HR     = "High Raided"
    LR     = "Low Raided"
    ST     = "Start Time"
    SP     = "Start Price"
    H      = "High"
    L      = "Low"
    ET     = "End Time"
    EP     = "End Price"
    HRT    = "High Raided Time"
    HRP    = "High Raided Price"
    HRVT   = "High Raided Violation Time"
    LPRHR  = "Lowest Price Reached High Raided"
    LPRHRT = "Lowest Price Reached High Raided Time"
    LRT    = "Low Raided Time"
    LRP    = "Low Raided Price"
    LRVT   = "Low Raided Violation Time"
    HPRLR  = "Highest Price Reached Low Raided"
    HPRLRT = "Highest Price Reached Low Raided Time"
    LTP    = "Long TP"
    LTPT   = "Long TP Time"
    LSL    = "Long SL"
    LSLT   = "Long SL Time"
    STP    = "Short TP"
    STPT   = "Short TP Time"
    SSL    = "Short SL"
    SSLT   = "Short SL Time"


// @function Identifies the last bar on the chart before a timeframe change
// @param userTF the timeframe you wish to calculate the last bar for, must be converted to integer using 'timeframe.in_seconds()'
// @returns bool true if bar on chart is last bar of higher TF, dalse if bar on chart is not last bar of higher TF

export isLastBar(simple int userTF) =>

    time("", -1) >= time_close(timeframe.from_seconds(userTF))


// @function returns necessaryData UDT for historical data access 
// @param atrTF user-selected timeframe ATR value. 
// @returns necessaryData UDT. Example declarationhistoricalData = necessaryData(ta.atr(14))//
// To access the "highArr" would then call "historicalData.highArr"
// @returns logZ. log return Z score, used for calculating order blocks.

export necessaryData(float atrTF) =>

    var historicalData = necessaryData.new(array.new<float>(), array.new<float>(), array.new<int>  (), 
                                           array.new<float>(), array.new<float>(), array.new<float>(), 
                                           array.new<int>  (), array.new<float>(), array.new<float>(), 
                                           array.new<float>(), array.new<float>()
                                             )

    historicalData.highArr      .unshift(high) ,                   historicalData.lowArr        .unshift(low), 
    historicalData.timeArr      .unshift(time) ,                   historicalData.binaryTimeArr .push   (time),                
    historicalData.closeArr     .unshift(close),                   historicalData.logArr        .push   (math.log(close / close[1]))
    historicalData.signArr      .unshift(math.sign(close - open)), historicalData.binaryCloseArr.push   (close), 
    historicalData.binaryOpenArr.push   (open), historicalData.atrTFarr.unshift(atrTF), historicalData.openArr.unshift(open)

    logZ           = (historicalData.logArr  .last() - historicalData.logArr  .avg()) / historicalData.logArr  .stdev()

    if historicalData.logArr.size() > 200 
        historicalData.logArr  .shift()


    [historicalData, logZ]


    
// @function creates neon like effect for box drawings 
// @param gradientBoxes an array.new<box>() to store the gradient boxes 
// @param idcolor color for the neon effect 
// @param timeStart left point of box
// @param bottom bottom of box price point 
// @param top top of box price point
// @param rightCoordinate right point of box
// @returns void

export method gradBoxes(array<box> gradientBoxes, color idColor, int timeStart, float bottom, float top, int rightCoordinate) =>
 
    if not na(gradientBoxes.first())

        for boxx in gradientBoxes 
            boxx.delete()
                            
    Range = math.abs(top - bottom) / 19, avg = math.avg(bottom, top)

    trueBottom = math.min(bottom, top)

    var nLine = line(na)

    nLine.delete()

    nLine := line.new(timeStart, avg, rightCoordinate, avg, width = 2, color = idColor, xloc = xloc.bar_time)

    for x = 0 to 19

        col = switch 

            x <= 9 => color.from_gradient(x, -1, 9, chart.bg_color, idColor)
            =>        color.from_gradient(x, 10, 20, idColor, chart.bg_color)

        gradientBoxes.set(x, box.new(timeStart, trueBottom + Range * (x + 1), rightCoordinate, trueBottom + Range * x, 
                             bgcolor = color.new(col, 85), border_color = color.new(col, 100), 
                             xloc    = xloc.bar_time))

// @function checks if recent trade is of specific name 
// @param tradeName, the name of the trade to target
// @returns bool true if recent trade id matches target name, false otherwise

export checkIfTraded(string tradeName) =>


    openTrades = strategy.opentrades - 1, closedTrades = strategy.closedtrades - 1

    strategy.opentrades.entry_id(openTrades) == tradeName and strategy.opentrades.entry_bar_index(openTrades) == bar_index 
     or strategy.closedtrades.entry_id(closedTrades) == tradeName and strategy.closedtrades.entry_bar_index(closedTrades) == bar_index 

// @function checks if recent closed trade is of specific name 
// @param tradeName, the name of the trade to target
// @returns bool true if recent closed trade id matches target name, false otherwise
        
export checkIfClosed(string tradeName) =>


    closedTrades = strategy.closedtrades - 1

    strategy.closedtrades.entry_id(closedTrades) == tradeName and strategy.closedtrades.entry_bar_index(closedTrades) == bar_index 
     or strategy.closedtrades.entry_id(closedTrades) == tradeName and strategy.closedtrades.exit_bar_index(closedTrades) == bar_index 


// @function custom ZZ to quickly determine market direction.
// @param atrMult an atr multiplier used to determine the required price move for a ZZ direction change
// @param finalTF the timeframe used for the atr calcuation
// @returns dir market direction. Up => 1, down => -1

export IQZZ(float atrMult, string finalTF) =>


    var point        = close
    var timeP        = time
    var dir          = 0
    
    atr = request.security("", finalTF, ta.atr(14))

    atr *= atrMult

    if dir == 1

        point := math.max(point, high)

        timeP := switch high == point 

            true => time 
            =>      timeP


        if low <= point - atr  and high != point

            dir   := -1 
            point := low
            timeP := time


    else if dir == -1


        point := math.min(low, point)

        timeP := switch low == point 
            true => time 
            =>      timeP

        if high >= point + atr and low != point

            dir   := 1 
            point := high 
            timeP := time

    if dir == 0 

        if high >= point + atr 

            dir   := 1
            point := high
            timeP := time 


        else if low <= point + atr

            dir   := -1 
            point := low
            timeP := time

    dir


// @function calculates and draws Break Of Structure 
// @param array<labelLine> id      uses labelLine UDT explained above to pair line of BoS with label of BoS  
// @param chart.point startPoint   the chart point of the start time of the broken level         
// @param getKeyPointTime      the actual time of startPoint, simplystartPoint.time               
// @param getKeyPointPrice   the actual time of startPoint, simplystartPoint.price                
// @param col                color of the BoS line / label  
// @param showBOS             whether to show label/line. This function still calculates internally for other ICT related concepts even if not drawn.                   
// @param isUp                whether BoS happened during price increase or price decrease.    
// @returnsvoid


export method drawBos(array<labelLine> id, chart.point startPoint, int getKeyPointTime, float getKeyPointPrice, color col, bool showBOS, bool isUp) => 

    avg = math.round(math.avg(getKeyPointTime, time))

    if showBOS

        position = switch isUp 

            true => label.style_label_up 
            =>      label.style_label_down

        id.push(
              labelLine.new(
                 line.new(startPoint, chart.point.from_time(time, getKeyPointPrice),
                                     color = col, 
                                     xloc  = xloc.bar_time,
                                     style = line.style_dotted
                                     ),

                 label.new(avg, getKeyPointPrice, xloc = xloc.bar_time, 
                                     color     = #00000000, 
                                     textcolor = col,
                                     text      = "BoS", 
                                     size      = size.tiny, 
                                     style     = position
                                     )))


// @function calculates and draws Market Structure Shift. This data is also used to calculate Rejection Blocks.
// @param array<labelLine> id      uses labelLine UDT explained above to pair line of MSS with label of MSS  
// @param chart.point startPoint   the chart point of the start time of the broken level         
// @param getKeyPointTime      the actual time of startPoint, simplystartPoint.time               
// @param getKeyPointPrice   the actual time of startPoint, simplystartPoint.price                
// @param col                color of the MSS line / label  
// @param showMSS             whether to show label/line. This function still calculates internally for other ICT related concepts even if not drawn.                   
// @param isUp                whether MSS happened during price increase or price decrease.    
// @param array<rejectionBlocks> upRejections  array containing upside rejection block data, array must be declared as array<rejectionBlocks>()
// @param array<rejectionBlocks> dnRejections  array containing downside rejection block data, array must be declared as array<rejectionBlocks>()
// @param highArr  array containing historical highs, should be taken from the UDT "necessaryData" defined above
// @param lowArr   array containing historical lows, should be taken from the UDT "necessaryData" defined above
// @param timeArr  array containing historical times, should be taken from the UDT "necessaryData" defined above
// @param closeArr  array containing historical closes, should be taken from the UDT "necessaryData" defined above
// @param openArr  array containing historical opens, should be taken from the UDT "necessaryData" defined above
// @param atrTFarr   array containing historical atr values (of user-selected TF), should be taken from the UDT "necessaryData" defined above
// @param upRejectionsPrices   array containing up rejections prices. Is sorted and used to determine selective looping for invalidations.
// @param dnRejectionsPrices   array containing down rejections prices. Is sorted and used to determine selective looping for invalidations.
// @returnsvoid


export method drawMSS(array<labelLine> id, chart.point startPoint, int getKeyPointTime, float getKeyPointPrice, color col,  bool showMSS, bool isUp,
                 array<rejectionBlocks> upRejections, array<rejectionBlocks> dnRejections, array<float> highArr, array<float> lowArr, 
                     array<int> timeArr, array<float> closeArr, array<float> openArr, array<float> atrTFarr,
                         array<float> upRejectionsPrices, array<float> dnRejectionsPrices) => 




    avg = math.round(math.avg(getKeyPointTime, time))

    if isUp 

        max = 0., maxTime = 0, isRejection = false, var bodyPrice = 0.

        for [i, data] in highArr 

            if data >= getKeyPointPrice

                max := math.max(max, data)

                if data == max 

                    maxTime := timeArr.get(i)

                    bodyPrice := math.max(closeArr.get(i), openArr.get(i))

                    isRejection := (math.abs(data - bodyPrice) >= atrTFarr.get(i) / 3)

            else 

                break 

        if max != 0 and isRejection 

            upRejections      .unshift(rejectionBlocks.new(chart.point.from_time(maxTime, max), bodyPrice))
            upRejectionsPrices.insert(upRejectionsPrices.binary_search_rightmost(max), max)


    else 

        min = 20e20, minTime = 0, isRejection = false, var bodyPrice = 0.

        for [i, data] in lowArr 

            if data <= getKeyPointPrice

                min := math.min(min, data)

                if data == min

                    minTime := timeArr.get(i)

                    bodyPrice := math.min(closeArr.get(i), openArr.get(i))

                    isRejection := (math.abs(data - bodyPrice) >= atrTFarr.get(i) / 3)

            else 

                break 

        if min != 20e20 and isRejection 

            dnRejections      .unshift(rejectionBlocks.new(chart.point.from_time(minTime, min), bodyPrice))
            dnRejectionsPrices.insert(dnRejectionsPrices.binary_search_rightmost(min), min)

    if showMSS

        position = switch isUp 

            true => label.style_label_up 
            =>      label.style_label_down

        id.push(
              labelLine.new(
                 line.new(startPoint, chart.point.from_time(time, getKeyPointPrice),
                                     color = col, 
                                     xloc  = xloc.bar_time
                                     ),

                 label.new(avg, getKeyPointPrice, xloc = xloc.bar_time, 
                                     color     = #00000000, 
                                     textcolor = col,
                                     text      = "MSS", 
                                     size      = size.tiny, 
                                     style     = position
                                     )))

// @function gets time of inputted price (compare) in an array of data 
// this is useful when the user-selected timeframe for ICT concepts is greater than the chart's timeframe 
// @param id the array of data to search through, to find which index has the same value as "compare"
// @param compare the target data point to find in the array
// @param timeArr array of historical times
// @returns the time that the data point in the array was recorded

export method getTime(array<float> id, float compare, array<int> timeArr) =>


    startTime = 0

    if id.size() > 0 

        for [i, v] in id 

            if v == compare 

                startTime := timeArr.get(i)
                break 

        startTime

    else

        time


// @function store bullish orderblock data 
// @param array<orderBlock> id an array for storing order block data and drawings. Declared using the UDT "orderBlock" as explained above.
// @param highArr array of historical highs
// @param signArr array of historical price direction "math.sign(close - open)"
// @param lowArr  array of historical lows
// @param timeArr   array of historical times 
// @param sign   orderblock direction, -1 => bullish, 1 => bearish
// @returns void

export method OB(array<orderBlock> id, array<float> highArr, array<float> signArr, array<float> lowArr, array<int> timeArr, int sign) =>

    for i = 1 to highArr.size() - 1
        if signArr.get(i) == sign

            getHigh = highArr.get(i)
            getLow  = lowArr .get(i)

            id.unshift(orderBlock.new(array.from(timeArr.get(i), getHigh, last_bar_time, getLow)))

            break



// @function executes the OTE strategy 
// @param chart.point OTEstart chart point of the first bar beginning the OTE setup
// @param future future time point for drawings
// @param closeArr array of historical closes
// @param highArr array of historical highs
// @param lowArr array of historical lows
// @param timeArr array of historical times
// @param longOTEPT user-selected long OTE profit target, please create an input.string() for this using the example below
// @param longOTESL    user-selected long OTE stop loss, please create an input.string() for this using the example below
// @param longOTElevel  long entry price of selected retracement ratio for OTE
// @param shortOTEPT user-selected short OTE profit target, please create an input.string() for this using the example below   
// @param shortOTESL    user-selected short OTE stop loss, please create an input.string() for this using the example below
// @param shortOTElevel  short entry price of selected retracement ratio for OTE
// @param structureDirection current market structure direction, this should be "Up" or "Down". This is used to cancel pending orders if market structure changes
// @param oteLongs input.bool() for whether OTE longs can be executed
// @param atrTF atr of the user-seleceted TF
// @param oteShorts input.bool() for whether OTE shorts can be executed
// @exampleInputs
	 // oteLongs        = input.bool(defval = false, title = "OTE Longs", group = "Optimal Trade Entry")
	 // longOTElevel    = input.float(defval = 0.79, title = "Long Entry Retracement Level", options = [0.79, 0.705, 0.62], group = "Optimal Trade Entry")
	 // longOTEPT       = input.string(defval = "-0.5", title = "Long TP", options = ["-0.5", "-1", "-2", "Swing High"], group = "Optimal Trade Entry")
	 // longOTESL       = input.int(defval = 0, title = "How Many Ticks Below Swing Low For Stop Loss", group = "Optimal Trade Entry")
	 // oteShorts       = input.bool(defval = false, title = "OTE Shorts", group = "Optimal Trade Entry")
	 // shortOTElevel   = input.float(defval = 0.79, title = "Short Entry Retracement Level", options = [0.79, 0.705, 0.62], group = "Optimal Trade Entry")
	 // shortOTEPT      = input.string(defval = "-0.5", title = "Short TP", options = ["-0.5", "-1", "-2", "Swing Low"], group = "Optimal Trade Entry")
	 // shortOTESL      = input.int(defval = 0, title = "How Many Ticks Above Swing Low For Stop Loss", group = "Optimal Trade Entry")
// @returns void (0)

export OTEstrat(chart.point OTEstart, int future, array<float> closeArr, array<float> highArr, array<float> lowArr, array<int>timeArr,
     string longOTEPT, int longOTESL, float longOTElevel, string shortOTEPT, int shortOTESL, float shortOTElevel, string structureDirection, 
         bool oteLongs, float atrTF, bool oteShorts) => 

    var highestPoint = 0., var lowestPoint = 20e20
    var highestPoinT = 0 , var lowestPoinT = 0

    var oteDrawings = OTEtimes.new(array.new<int>(), array.new<int>())

    if OTEstart.time != OTEstart.time[1] 
        highestPoint := 0, lowestPoint := 20e20

    var map <string, float> OTElevels = map.new<string, float>()

    openTrades = strategy.opentrades - 1, closedTrades = strategy.closedtrades - 1

    keys = OTElevels.keys()

    highestPoint := math.max(highestPoint, high)
    lowestPoint  := math.min(lowestPoint, low)

    if highestPoint == high
        highestPoinT := time 
        strategy.cancel("Long OTE")

    if lowestPoint == low 
        lowestPoinT := time
        strategy.cancel("Short OTE")

    if strategy.position_size != 0
        strategy.cancel("Long OTE")
        strategy.cancel("Short OTE")

    if not na(oteDrawings.tpLineLong)

        oteDrawings.tpLineLong .set_x2(future)
        oteDrawings.tpLabelLong.set_x (future)
        oteDrawings.slLineLong .set_x2(future)
        oteDrawings.slLabelLong.set_x (future)

        if checkIfClosed("Long OTE")

            switch strategy.closedtrades.exit_price(closedTrades) > strategy.closedtrades.entry_price(closedTrades)

                true => 

                     oteDrawings.slLineLong .delete(), 
                     oteDrawings.slLabelLong.delete(), 

                     oteDrawings.tpLineLong  := line (na),
                     oteDrawings.tpLabelLong := label(na)

                => 

                     oteDrawings.tpLineLong .delete(), 
                     oteDrawings.tpLabelLong.delete(),  

                     oteDrawings.slLineLong  := line (na),
                     oteDrawings.slLabelLong := label(na)


    if checkIfTraded("Long OTE")

        oteDrawings.upTimes.push(int(OTElevels.get("Long OTE Highest PoinT")))
            
        entry = OTElevels.get("Long OTE Entry")
        for i = 1 to closeArr.size() - 1
    
            if highArr.get(i) >= entry and lowArr.get(i) <= entry or highArr.get(i) <= entry 
            
                getTime = timeArr.get(i)
    
                line.new (getTime, entry, time, entry, color = #74ffbc, xloc = xloc.bar_time, style = line.style_dotted, width = 2)
                label.new(math.round(math.avg(getTime, time)), entry, color = #00000000, xloc = xloc.bar_time, 
                                                 text = str.tostring(longOTElevel),
                                                 textcolor = #74ffbc, 
                                                 style = label.style_label_up, 
                                                 size = size.small
                                                 )
    
                getTP = OTElevels.get("Long OTE TP")
                getSL = OTElevels.get("Long OTE SL")

                oteDrawings.tpLineLong := line.new(int(OTElevels.get("Long OTE Highest PoinT")), getTP, future, getTP, 
                                     color = #74ffbc, xloc = xloc.bar_time, style = line.style_solid, width = 2)

                oteDrawings.tpLabelLong := label.new(future, getTP, text = longOTEPT, style = label.style_label_lower_right,
                                     textcolor = #74ffbc, xloc = xloc.bar_time, color = #00000000, size = size.small)

                oteDrawings.slLineLong := line.new(int(OTElevels.get("Long OTE Start Time")), getSL, future, getSL, 
                                     color = color.red, xloc = xloc.bar_time, style = line.style_solid, width = 2)

                txt = switch longOTESL

                    0 => "Swing Low"
                    =>   "Swing Low - " + str.tostring(longOTESL) + " Ticks"

                oteDrawings.slLabelLong := label.new(future, getSL, text = txt, style = label.style_label_upper_right,
                                     textcolor = color.red, xloc = xloc.bar_time, color = #00000000, size = size.small)

                if checkIfClosed("Long OTE")

                    switch strategy.closedtrades.exit_price(closedTrades) > strategy.closedtrades.entry_price(closedTrades)
                    
                        true => 

                             oteDrawings.slLineLong .delete(), 
                             oteDrawings.slLabelLong.delete(), 

                             oteDrawings.tpLineLong  := line (na),
                             oteDrawings.tpLabelLong := label(na) 

                        => 

                             oteDrawings.tpLineLong .delete(), 
                             oteDrawings.tpLabelLong.delete(),  

                             oteDrawings.slLineLong  := line (na),
                             oteDrawings.slLabelLong := label(na)


                points = array.from(     chart.point.from_time(int(OTElevels.get("Long OTE Start Time"   )), OTElevels.get("Long OTE Start Price"  )),
                                         chart.point.from_time(int(OTElevels.get("Long OTE Highest PoinT")), OTElevels.get("Long OTE Highest Point")), 
                                                                             chart.point.from_time(time, entry))
    
                polyline.new(points, xloc = xloc.bar_time, line_color = color.rgb(128, 116, 255))

                for values in keys 

                    if str.contains(values, "Long")

                        OTElevels.put(values, na)

                break 


    if not na(oteDrawings.tpLineShort)

        oteDrawings.tpLineShort .set_x2(future)
        oteDrawings.tpLabelShort.set_x (future)
        oteDrawings.slLineShort .set_x2(future)
        oteDrawings.slLabelShort.set_x (future)

        if checkIfClosed("Short OTE")

            switch strategy.closedtrades.exit_price(closedTrades) < strategy.closedtrades.entry_price(closedTrades)

                true => 

                     oteDrawings.slLineShort .delete(), 
                     oteDrawings.slLabelShort.delete(), 

                     oteDrawings.tpLineShort  := line (na),
                     oteDrawings.tpLabelShort := label(na)

                => 

                     oteDrawings.tpLineShort .delete(), 
                     oteDrawings.tpLabelShort.delete(),  

                     oteDrawings.slLineShort  := line (na),
                     oteDrawings.slLabelShort := label(na)


    if checkIfTraded("Short OTE")

        oteDrawings.dnTimes.push(int(OTElevels.get("Short OTE Lowest PoinT")))
            
        entry = OTElevels.get("Short OTE Entry")

        for i = 1 to closeArr.size() - 1
    
            if highArr.get(i) >= entry and lowArr.get(i) <= entry or lowArr.get(i) >= entry 
            
                getTime = timeArr.get(i)
    
                line.new (getTime, entry, time, entry, color = color.rgb(255, 116, 116), xloc = xloc.bar_time, style = line.style_dotted, width = 2)
                label.new(math.round(math.avg(getTime, time)), entry, color = #00000000, xloc = xloc.bar_time, 
                                                 text = str.tostring(shortOTElevel),
                                                 textcolor = color.rgb(255, 116, 116), 
                                                 style = label.style_label_down, 
                                                 size = size.small
                                                 )
    
                getTP = OTElevels.get("Short OTE TP")
                getSL = OTElevels.get("Short OTE SL")

                oteDrawings.tpLineShort := line.new(int(OTElevels.get("Short OTE Lowest PoinT")), getTP, future, getTP, 
                                     color = #74ffbc, xloc = xloc.bar_time, style = line.style_solid, width = 2)

                oteDrawings.tpLabelShort := label.new(future, getTP, text = shortOTEPT, style = label.style_label_upper_right,
                                     textcolor = #74ffbc, xloc = xloc.bar_time, color = #00000000, size = size.small)

                oteDrawings.slLineShort := line.new(int(OTElevels.get("Short OTE Start Time")), getSL, future, getSL, 
                                     color = color.red, xloc = xloc.bar_time, style = line.style_solid, width = 2)

                txt = switch shortOTESL

                    0 => "Swing High"
                    =>   "Swing How + " + str.tostring(shortOTESL) + " Ticks"

                oteDrawings.slLabelShort := label.new(future, getSL, text = txt, style = label.style_label_lower_right,
                                     textcolor = color.red, xloc = xloc.bar_time, color = #00000000, size = size.small)

                if checkIfClosed("Short OTE") 

                    switch strategy.closedtrades.exit_price(closedTrades) < strategy.closedtrades.entry_price(closedTrades)
                    
                        true => 

                             oteDrawings.slLineShort .delete(), 
                             oteDrawings.slLabelShort.delete(), 

                             oteDrawings.tpLineShort  := line (na),
                             oteDrawings.tpLabelShort := label(na) 

                        => 

                             oteDrawings.tpLineShort .delete(), 
                             oteDrawings.tpLabelShort.delete(),  

                             oteDrawings.slLineShort  := line (na),
                             oteDrawings.slLabelShort := label(na)


                points = array.from(     chart.point.from_time(int(OTElevels.get("Short OTE Start Time"  )), OTElevels.get("Short OTE Start Price" )),
                                         chart.point.from_time(int(OTElevels.get("Short OTE Lowest PoinT")), OTElevels.get("Short OTE Lowest Point")), 
                                                                     chart.point.from_time(time, entry))
    
                polyline.new(points, xloc = xloc.bar_time, line_color = color.rgb(128, 116, 255))

                for values in keys 

                    if str.contains(values, "Short")

                        OTElevels.put(values, na)
    
                break 


    if structureDirection == "Up" 

        strategy.cancel("Short OTE")

        if strategy.opentrades.entry_id(openTrades) != "Short OTE"    

            for values in keys 

                if str.contains(values, "Short")

                    OTElevels.put(values, na)

        if oteLongs

            if highestPoint - OTEstart.price >= atrTF 

                if not oteDrawings.upTimes.includes(highestPoinT)

                    entry = math.round_to_mintick(highestPoint - ((highestPoint - OTEstart.price) * longOTElevel))

                    tp    = switch longOTEPT 

                        "Swing High" => math.round_to_mintick(highestPoint)
                        =>              math.round_to_mintick(highestPoint - ((highestPoint - OTEstart.price) * str.tonumber(longOTEPT)))

                    sl    = math.round_to_mintick(OTEstart.price - longOTESL * syminfo.mintick)


                    if close >= entry and barstate.isconfirmed and strategy.opentrades == 0

                        OTElevels.put("Long OTE Entry", entry)
                        OTElevels.put("Long OTE TP"   , tp)
                        OTElevels.put("Long OTE SL"   , sl)
                        OTElevels.put("Long OTE Start Time", OTEstart.time)
                        OTElevels.put("Long OTE Start Price", OTEstart.price)
                        OTElevels.put("Long OTE Highest Point", highestPoint)
                        OTElevels.put("Long OTE Highest PoinT", highestPoinT)

                        strategy.entry("Long OTE", strategy.long, comment = "OTE Long", limit = entry)
                        strategy.exit("Long OTE Exit", "Long OTE", limit = tp, stop = sl, comment_profit = "Long OTE Profit", comment_loss = "Long OTE Loss")

            if close < OTEstart.price

                oteDrawings.upTimes.push(highestPoinT)

    else

        strategy.cancel("Long OTE")

        if strategy.opentrades.entry_id(openTrades) != "Long OTE"    

            for values in keys 

                if str.contains(values, "Long")

                    OTElevels.put(values, na)


        if oteShorts
            if OTEstart.price - lowestPoint >= atrTF

                if not oteDrawings.dnTimes.includes(lowestPoinT)

                    entry = math.round_to_mintick(((OTEstart.price - lowestPoint) * shortOTElevel) + lowestPoint)

                    tp    = switch shortOTEPT 

                        "Swing Low" =>  math.round_to_mintick(lowestPoint)
                        =>              math.round_to_mintick(lowestPoint - ((lowestPoint - OTEstart.price) * str.tonumber(shortOTEPT)))

                    sl    = math.round_to_mintick(OTEstart.price + shortOTESL * syminfo.mintick)


                    if close <= entry and barstate.isconfirmed and strategy.opentrades == 0

                        OTElevels.put("Short OTE Entry", entry)
                        OTElevels.put("Short OTE TP"   , tp)
                        OTElevels.put("Short OTE SL"   , sl)
                        OTElevels.put("Short OTE Start Time", OTEstart.time)
                        OTElevels.put("Short OTE Start Price", OTEstart.price)
                        OTElevels.put("Short OTE Lowest Point", lowestPoint)
                        OTElevels.put("Short OTE Lowest PoinT", lowestPoinT)


                        strategy.entry("Short OTE", strategy.short, comment = "OTE Short", limit = entry)
                        strategy.exit("Short OTE Exit", "Short OTE", limit = tp, stop = sl, comment_profit = "Short OTE Profit", comment_loss = "Short OTE Loss")

            if close > OTEstart.price

                oteDrawings.dnTimes.push(lowestPoinT)

    0


        
// @function calculates and draws dispacements
// @param logZ  log return of current price, used to determine a "significant price move" for a displacement
// @param atrTFreg atr of user-seleceted timeframe 
// @param highArr array of historical highs
// @param timeArr array of historical times
// @param lowArr array of historical lows
// @param upDispShow amount of historical upside displacements to show
// @param dnDispShow amount of historical downside displacements to show
// @param masterCoords a <string, float> map to push the most recent displacement prices into, useful for having key levels in one data structure
// @param labelLevels used to determine label placement for the displacement, can be inside box, outside box, or none, example below
// @param dispUpcol upside displacement color
// @param rightCoordinate  future time for displacement drawing, best is "last_bar_time"
// @param dispDncol downside displacement color
// @param noBorders input.bool() to remove box borders, example below 
// @exampleInputs
	// labelLevels     = input.string(defval = "Inside" , title = "Box Label Placement", options = ["Inside", "Outside", "None"])
	// noBorders       = input.bool(defval = false, title = "No Borders On Levels")
// @returns void
 


export displacement(float logZ, float atrTFreg, array<float> highArr, array<int> timeArr, array<float> lowArr, int upDispShow, int dnDispShow,
     map<string, float> masterCoords, string labelLevels, color dispUpcol, int rightCoordinate, color dispDncol, bool noBorders) => 

    var upVolatility = array.new<float>(), var dnVolatility = array.new<float>()

    var upDisplacement = array.new<displacement>()
    var dnDisplacement = array.new<displacement>()

    if logZ >= 1 and high <= close + atrTFreg * .5
        upVolatility.push(logZ)
    else 
        if upVolatility.size() >= 3 

            size    = upVolatility.size() + 1

            getHigh = highArr.get(size)

            upDisplacement.unshift(
                     displacement.new(getHigh, low, timeArr.get(size)
                             
                     ))

        upVolatility.clear()


    if logZ <= -1 and low >= close - atrTFreg * .5
        dnVolatility.push(logZ)

    else

        if dnVolatility.size() >= 3 

            size    = dnVolatility.size() + 1

            getLow = lowArr.get(size)

            dnDisplacement.unshift(
                     displacement.new(high, getLow, timeArr.get(size)
                             
                     ))

        dnVolatility.clear()

    if upDisplacement.size() > 0 
        for i = upDisplacement.size() - 1 to 0
            if close < upDisplacement.get(i).highPrice
                upDisplacement.remove(i).displacementBox.delete()

    if dnDisplacement.size() > 0 
        for i = dnDisplacement.size() - 1 to 0
            if close > dnDisplacement.get(i).lowPrice
                dnDisplacement.remove(i).displacementBox.delete()


    if barstate.islast 

        if upDisplacement.size() > 0

            for i = 0 to upDisplacement.size() - 1

                getDisp = upDisplacement.get(i)

                getDisp.displacementBox.delete()

                if labelLevels == "Outside"

                    getDisp.displacementLab.delete()

                if i < upDispShow 


                    txt = switch labelLevels == "Inside"

                        true => "DP" 
                        =>      ""
        
                    var borderTransp = switch noBorders
                    
                        true => 100 
                        =>      25

                    [bordCol, bgCol] = switch i == 0

                        true => [#00000000, #00000000]
                        =>      [color.new(dispUpcol, borderTransp), color.new(dispUpcol, 75)]


                    getDisp.displacementBox := box.new(getDisp.timeAtPrice, getDisp.highPrice, 
                                                 rightCoordinate, getDisp.lowPrice, 
                                                 xloc         = xloc.bar_time, 
                                                 bgcolor      = bgCol,
                                                 border_color = bordCol,
                                                 text         = txt,
                                                 text_halign  = text.align_right, 
                                                 text_size    = size.auto,
                                                 text_color   = color.new(chart.fg_color, 25) 
                                                 )

                    if labelLevels == "Outside"

                        getDisp.displacementLab := label.new(rightCoordinate, math.avg(getDisp.highPrice, getDisp.lowPrice), 
                                                                 color     = #00000000, 
                                                                 textcolor = dispUpcol, 
                                                                 text      = "DP", 
                                                                 style     = label.style_label_left, 
                                                                 xloc      = xloc.bar_time, 
                                                                 size      = size.tiny 
                                                                 )


                    if i == 0

                        var gradientBoxes = array.new<box>(20)

                        gradientBoxes.gradBoxes(dispUpcol, getDisp.timeAtPrice, getDisp.lowPrice, getDisp.highPrice, rightCoordinate)


                    if na(masterCoords.get("Up Displacement")) and upDispShow != 0

                        masterCoords.put("Up Displacement", math.avg(getDisp.highPrice, getDisp.lowPrice))

                    
        if dnDisplacement.size() > 0

            for i = 0 to dnDisplacement.size() - 1

                getDisp = dnDisplacement.get(i)

                getDisp.displacementBox.delete()

                if labelLevels == "Outside"

                    getDisp.displacementLab.delete()

                if i < dnDispShow 

                    col = color.from_gradient(getDisp.lowPrice, close, close + atrTFreg * 10, color.new(dispDncol, 25), color.new(dispDncol, 90))

                    txt = switch labelLevels == "Inside"

                        true => "DP" 
                        =>      ""
        
                    var borderTransp = switch noBorders
                    
                        true => 100 
                        =>      25

                    [bordCol, bgCol] = switch i == 0

                        true => [#00000000, #00000000]
                        =>      [color.new(dispDncol, borderTransp), color.new(dispDncol, 75)]


                    getDisp.displacementBox := box.new(getDisp.timeAtPrice, getDisp.highPrice, 
                                                 rightCoordinate, getDisp.lowPrice, 
                                                 xloc         = xloc.bar_time, 
                                                 bgcolor      = bgCol,
                                                 border_color = bordCol,
                                                 text         = txt,
                                                 text_halign  = text.align_right,
                                                 text_size    = size.auto,
                                                 text_color   = color.new(chart.fg_color, 25) 
                                                 )

                    if labelLevels == "Outside"

                        getDisp.displacementLab := label.new(rightCoordinate, math.avg(getDisp.highPrice, getDisp.lowPrice), 
                                                                 color     = #00000000, 
                                                                 textcolor = dispDncol, 
                                                                 text      = "DP", 
                                                                 style     = label.style_label_left, 
                                                                 xloc      = xloc.bar_time, 
                                                                 size      = size.tiny 
                                                                 )


                    if i == 0

                        var gradientBoxes = array.new<box>(20)

                        gradientBoxes.gradBoxes(dispDncol, getDisp.timeAtPrice, getDisp.lowPrice, getDisp.highPrice, rightCoordinate)


                    if na(masterCoords.get("Down Displacement")) and upDispShow != 0

                        masterCoords.put("Down Displacement", math.avg(getDisp.highPrice, getDisp.lowPrice))



// @function unshift strong low data to array<strongPoints> id
// @param array<strongPoints> id an array declared using the "strongPoints" UDT
// @param startIndex the starting index for the timeArr array of the UDT "necessaryData". 
	 	 	 //this point should start from at least 1 pivot prior to find the low before an upside BoS
// @param timeArr array of historical times
// @param lowArr array of historical lows
// @param strongLowPoints array of strong low prices. Used to retrieve highest strong low price and see if need for 
        //  removal of invalidated strong lows
// @returns void

export method getStrongLow(array<strongPoints> id, int startIndex, array<int> timeArr, array<float> lowArr, array<float> strongLowPoints) =>


    getLow = 20e20, getLowTime = 0

    for i = startIndex to 0 

        getLowArr = lowArr.get(i)

        getLow := math.min(getLow, getLowArr)

        if getLow == getLowArr

            getLowTime := timeArr.get(i)

    strongLowPoints.unshift(getLow)

    id.unshift(strongPoints.new(price = getLow, timeAtprice = getLowTime))


// @function unshift strong high data to array<strongPoints> id
// @param array<strongPoints> id an array declared using the "strongPoints" UDT
// @param startIndex the starting index for the timeArr array of the UDT "necessaryData". 
	 	 	 //this point should start from at least 1 pivot prior to find the high before a downside BoS
// @param timeArr array of historical times
// @param highArr array of historical highs
// @param stronghighPoints array of strong high prices. Used to retrieve lowst strong high price and see if need for 
        //  removal of invalidated strong highs
// @returns void

export method getStrongHigh(array<strongPoints> id, int startIndex, array<int> timeArr, array<float> highArr, array<float> strongHighPoints) =>

    getHigh = 0., getHighTime = 0

    for i = startIndex to 0 

        gethighArr = highArr.get(i)

        getHigh := math.max(getHigh, gethighArr)

        if getHigh == gethighArr

            getHighTime := timeArr.get(i)


    strongHighPoints.unshift(getHigh)

    id.unshift(strongPoints.new(price = getHigh, timeAtprice = getHighTime))

    

// @function used to calculate recent equal highs or equal lows
// @param highArr array of historical highs
// @param lowArr  array of historical lows
// @param timeArr   array of historical times
// @param rightCoordinate         a future time (right for boxes, x2 for lines)   
// @param equalHighsCol user-selected color for equal highs drawings
// @param equalLowsCol user-selected color for equal lows drawings
// @param liteMode optional for a lite mode version of an ICT strategy. For more control over drawings leave as "True", "False" will apply neon effects
// @returns void

export equalLevels(array<float> highArr, array<float> lowArr, array<int> timeArr, int rightCoordinate, color equalHighsCol, color equalLowsCol, bool liteMode) => 

    var equalHighsValues = equalLevelsDraw.new(levels = array.new<float>(), radiate = array.new<label>(), times = array.new<int>())
    var equalLowsValues  = equalLevelsDraw.new(levels = array.new<float>(), radiate = array.new<label>(), times = array.new<int>())

    if not na(equalHighsValues)

        if equalHighsValues.levels.size() > 0

            equalHighsValues.connector   .delete()
            equalHighsValues.connectorLab.delete()
            equalHighsValues.levels      .clear()
            equalHighsValues.times       .clear()

            if equalHighsValues.radiate.size() > 0

                for i = 0 to equalHighsValues.radiate.size() - 1

                    equalHighsValues.radiate.shift().delete()

    if not na(equalLowsValues)

        if equalLowsValues.levels.size() > 0

            equalLowsValues.connector   .delete()
            equalLowsValues.connectorLab.delete()
            equalLowsValues.levels      .clear()
            equalLowsValues.times       .clear()

            if equalLowsValues.radiate.size() > 0

                for i = 0 to equalLowsValues.radiate.size() - 1

                    equalLowsValues.radiate.shift().delete()


    var atrArr = array.new<float>()

    atrArr.unshift(ta.atr(14) / 15)

    if barstate.islast 

        start = switch barstate.isconfirmed

            true => 0 
            =>      1

        min = math.min(100, highArr.size())

        sliceHighs = highArr.slice(start, min)
        sliceLows  = lowArr .slice(start, min)
        sliceATR   = atrArr .slice(start, min)
        sliceTime  = timeArr.slice(start, min)

        highFound = false, lowFound = false

        if sliceHighs.size() > 1

            for i = sliceHighs.size() - 1 to 1

                getInitialHigh = sliceHighs.get(i), getAtr = sliceATR.get(i), getInitialTime = sliceTime.get(i)

                for x = i - 1 to 0

                    compare = sliceHighs.get(x), compareTime = sliceTime.get(x)

                    if compare > getInitialHigh - getAtr and compare < getInitialHigh + getAtr

                        if equalHighsValues.levels.size() == 0 

                            equalHighsValues.levels.push(getInitialHigh)
                            equalHighsValues.times .push(getInitialTime)

                            equalHighsValues.startTime := getInitialTime

                        equalHighsValues.levels.push(compare)
                        equalHighsValues.times .push(compareTime)

                        highFound := true

                    if compare > getInitialHigh + getAtr 
                    
                        equalHighsValues.levels.clear()
                        equalHighsValues.times .clear()
                        equalHighsValues.startTime := int(na)
                        highFound := false

                        break 

                if highFound 

                    getAvg = equalHighsValues.levels.avg()

                    equalHighsValues.connector    := line.new(equalHighsValues.startTime, getAvg, rightCoordinate, getAvg, xloc = xloc.bar_time, 
                                                             color = equalHighsCol, 
                                                             style = line.style_dotted
                                                             )

                    equalHighsValues.connectorLab := label.new(math.round(math.avg(equalHighsValues.startTime, equalHighsValues.times.last())),
                                                         getAvg, 
                                                         xloc      = xloc.bar_time, 
                                                         color     = #00000000, 
                                                         textcolor = equalHighsCol, 
                                                         style     = label.style_label_down, 
                                                         size      = size.tiny, 
                                                         text      = "Equal Highs"
                                                         )

                    if not liteMode

                        for [x, price] in equalHighsValues.levels
                        
                            getTime = equalHighsValues.times.get(x)

                            equalHighsValues.radiate.push(label.new(getTime, price, xloc = xloc.bar_time,
                                                                     text      = "•", 
                                                                     style     = label.style_text_outline,
                                                                     color     = color.new(equalHighsCol, 80),
                                                                     textcolor = equalHighsCol, 
                                                                     size      = size.normal
                                                                             ))

                            equalHighsValues.radiate.push(label.new(getTime, price, xloc = xloc.bar_time,
                                                                     text      = "•", 
                                                                     style     = label.style_text_outline,
                                                                     color     = color.new(equalHighsCol, 80),
                                                                     textcolor = equalHighsCol, 
                                                                     size      = size.normal
                                                                             ))


                    break


        if sliceLows.size() > 1

            for i = sliceLows.size() - 1 to 1

                getInitialLow = sliceLows.get(i), getAtr = sliceATR.get(i), getInitialTime = sliceTime.get(i) 

                for x = i - 1 to 0

                    compare = sliceLows.get(x), compareTime = sliceTime.get(x)

                    if compare > getInitialLow - getAtr and compare < getInitialLow + getAtr

                        if equalLowsValues.levels.size() == 0 

                            equalLowsValues.levels.push(getInitialLow)
                            equalLowsValues.times .push(getInitialTime)

                            equalLowsValues.startTime := getInitialTime

                        equalLowsValues.levels.push(compare)
                        equalLowsValues.times .push(compareTime)

                        lowFound := true

                    if compare < getInitialLow - getAtr

                        equalLowsValues.levels.clear()
                        equalLowsValues.times .clear()

                        equalLowsValues.startTime := int(na)                        
                        lowFound := false

                        break 

                if lowFound 

                    getAvg = equalLowsValues.levels.avg()

                    equalLowsValues.connector    := line.new(equalLowsValues.startTime, getAvg, rightCoordinate, getAvg, xloc = xloc.bar_time, 
                                                 color = equalLowsCol, 
                                                 style = line.style_dotted
                                                 )

                    equalLowsValues.connectorLab := label.new(math.round(math.avg((equalLowsValues.startTime), equalLowsValues.times.last())),
                                                         getAvg, 
                                                         xloc      = xloc.bar_time, 
                                                         color     = #00000000, 
                                                         textcolor = equalLowsCol, 
                                                         style     = label.style_label_up, 
                                                         size      = size.tiny, 
                                                         text      = "Equal Lows"
                                                         )

                    if not liteMode

                        for [x, price] in equalLowsValues.levels
                        
                            getTime = equalLowsValues.times.get(x)

                            equalLowsValues.radiate.push(label.new(getTime, price, xloc = xloc.bar_time,
                                                                     text      = "•", 
                                                                     style     = label.style_text_outline,
                                                                     color     = color.new(equalLowsCol, 80),
                                                                     textcolor = equalLowsCol, 
                                                                     size      = size.normal
                                                                             ))

                            equalLowsValues.radiate.push(label.new(getTime, price, xloc = xloc.bar_time,
                                                                     text      = "•", 
                                                                     style     = label.style_text_outline,
                                                                     color     = color.new(equalLowsCol, 80),
                                                                     textcolor = equalLowsCol, 
                                                                     size      = size.normal
                                                                             ))



                    break

// @function used to quickly determine if a user-inputted time range is currently active in NYT time
// @param timeString a time range 
// @returns true if session is active, false if session is inactive

export quickTime(string timeString) => 


    not na(time("1", timeString, "America/New_York"))

// @function used to calculate and draw session macros 
// @param showMacros an input.bool() or simple bool to determine whether to activate the function
// @param noBorders  an input.bool() to determine whether the box anchored to the session should have borders
// @returns void

export macros(bool showMacros, bool noBorders) => 

    if showMacros and timeframe.in_seconds("") <= timeframe.in_seconds("5")

        macro = macros.new(array.from(quickTime("0233-0300"), 
                                      quickTime("0403-0430"), 
                                      quickTime("0850-0910"), 
                                      quickTime("0950-1010"), 
                                      quickTime("1050-1110"), 
                                      quickTime("1150-1210"), 
                                      quickTime("1310-1340"), 
                                      quickTime("1515-1545")
                                      ),

                           sessionTimes = array.from("London\n02:33-03:00",
                                      "London\n04:03-04:30",
                                      "NY AM\n08:50-09:10",
                                      "NY AM\n09:50-10:10",
                                      "NY AM\n10:50-11:10",
                                      "NY Lunch\n11:50-12:10",
                                      "NY PM\n13:10-13:40",
                                      "NY Last Hr.\n15:15-15:45"
                                      ))

        var macroPrices = macros.new(na, matrix.new<float>(8, 5), sessionLines = matrix.new<line>(8, 2))

        var macroBoxes = array.new<box>(), var macroLabels = array.new<label>()

        for [i, session] in macro.sessions

            if session

                if na(macroPrices.prices.get(i, 0))
                    macroPrices.prices.set(i, 0, open)
                    macroPrices.prices.set(i, 4, time)


                macroPrices.prices.set(i, 1, close)
                macroPrices.prices.set(i, 2, math.max(high, nz(macroPrices.prices.get(i, 2))))
                macroPrices.prices.set(i, 3, math.min(low , nz(macroPrices.prices.get(i, 3), 20e20)))

            else 

                if not na(macroPrices.prices.get(i, 0))

                    getTop = macroPrices.prices.get(i, 2)
                    getBot = macroPrices.prices.get(i, 3)

                    borderTransp = switch noBorders 
                        true => 100 
                        =>      25

                    macroBoxes.unshift(box.new(left = int(macroPrices.prices.get(i, 4)), top = getTop, right = time, 
                                                     bottom       = getBot,
                                                     xloc         = xloc.bar_time,
                                                     bgcolor      = color.new(chart.fg_color, 80),
                                                     border_color = color.new(chart.fg_color, borderTransp), 
                                                     border_style = line.style_dashed
                                                     ))

                    macroLabels.unshift(label.new(math.round(math.avg(macroPrices.prices.get(i, 4), time)), getTop, 
                                                     xloc       = xloc.bar_time, 
                                                     color      = #00000000, 
                                                     textcolor  = chart.fg_color, 
                                                     text       = macro.sessionTimes.get(i),
                                                     size       = size.tiny
                                                     ))
                        
                    if macroBoxes.size() > 100
                        macroBoxes .pop().delete()
                        macroLabels.pop().delete()

                    if last_bar_time - time <= 86400 * 1000 * 2

                        for lines in macroPrices.sessionLines

                            lines.get(0).delete()
                            lines.get(1).delete()

                        macroPrices.sessionLines.set(i, 0, 
                                         line.new(time, getTop, last_bar_time, getTop, color = chart.fg_color, 
                                                             style = line.style_dotted, 
                                                             xloc  = xloc.bar_time
                                         ))


                        macroPrices.sessionLines.set(i, 1, 
                                         line.new(time, getBot, last_bar_time, getBot, color = chart.fg_color, 
                                                             style = line.style_dotted, 
                                                             xloc  = xloc.bar_time
                                         ))


                    macroPrices.prices.fill(na, i, i + 1, 0, 5)


// @function use to calculate HTF po3 candle 
// @tip only call this function on "barstate.islast"
// @param simple string tf user-inputted timeframe for the po3 candle
// @param left the left point of the candle, calculated as bar_index + left, 
// @param right :the right point of the candle, calculated as bar_index + right, 
// @param show input.bool() whether to show the po3 candle or not
// @returns void

export po3(simple string tf, int left, int right, bool show) => 

    if show

		middle = math.round(math.avg(right, left))

        var po3 = po3data.new(high, low, open, close, box(na), array.new<line>(2), array.new<label>(5))

        po3.dHigh  := math.max(high, po3.dHigh)
        po3.dLow   := math.min(low, po3.dLow)
        po3.dClose := close

        var po3Poly = array.new<polyline>(4)

        if timeframe.change(tf)

            po3.dHigh := high 
            po3.dLow  := low 
            po3.dOpen := open
            

        if barstate.islast

            bodyCol = switch math.sign(po3.dClose - po3.dOpen) 

                1  => #74ffbc
                -1 => color.rgb(255, 116, 116)
                =>    color.gray

            top = math.max(po3.dClose, po3.dOpen)
            bot = math.min(po3.dClose, po3.dOpen)

            if na(po3.po3box)

                po3.po3box := box.new(bar_index + left, top, bar_index + right, bot, 
                     border_color = color.new(color.gray, 25), bgcolor = color.new(bodyCol, 25))



            po3.po3box.set_lefttop    (bar_index + left, top)
            po3.po3box.set_rightbottom(bar_index + right, bot)
            po3.po3box.set_bgcolor(color.new(bodyCol, 25))

            coords = array.from( chart.point.from_index(bar_index + left , top),
                                 chart.point.from_index(bar_index + right, top),
                                 chart.point.from_index(bar_index + right, bot), 
                                 chart.point.from_index(bar_index + left , bot))

 
            for poly in po3Poly 
                poly.delete()

            po3Poly.set(0, polyline.new(coords, line_width = 3 , line_color = color.new(bodyCol, 80), xloc = xloc.bar_index, closed = true))
            po3Poly.set(1, polyline.new(coords, line_width = 6, line_color = color.new(bodyCol, 95), xloc = xloc.bar_index, closed = true))


            coords := array.from(chart.point.from_index(bar_index + middle, top), chart.point.from_index(bar_index + middle, po3.dHigh))

            po3Poly.set(2, polyline.new(coords, line_width = 3 , line_color = color.new(color.gray, 80), xloc = xloc.bar_index, closed = true))

            coords := array.from(chart.point.from_index(bar_index + middle, bot), chart.point.from_index(bar_index + middle, po3.dLow))

            po3Poly.set(3, polyline.new(coords, line_width = 3 , line_color = color.new(color.gray, 80), xloc = xloc.bar_index, closed = true))


            if na(po3.po3line.first())

                po3.po3line.set(0, line.new(bar_index + middle, top, bar_index + middle, po3.dHigh, color = color.gray))
                po3.po3line.set(1, line.new(bar_index + middle, bot, bar_index + middle, po3.dLow, color = color.gray))

            po3.po3line.first().set_xy1(bar_index + middle, top)
            po3.po3line.first().set_xy2(bar_index + middle, po3.dHigh)

            po3.po3line.get(1).set_xy1(bar_index + middle, bot)
            po3.po3line.get(1).set_xy2(bar_index + middle, po3.dLow)


            if timeframe.change("")

                for lab in po3.po3Labels
                    lab.delete()

            for i = 0 to 4 

                y = switch i % 5

                    0 => po3.dOpen
                    1 => po3.dClose
                    2 => po3.dHigh
                    3 => po3.dLow
                    =>   po3.dHigh

                if i != 4

                    if na(po3.po3Labels.get(i))

                        po3.po3Labels.push(label.new(bar_index + right, y, text = str.tostring(y, format.mintick), 
                                                 color     = #00000000, 
                                                 style     = label.style_label_left, 
                                                 textcolor = color.new(chart.fg_color, 25),
                                                 size      = size.tiny
                                                 ))

                    else 

                        po3.po3Labels.get(i).set_xy(bar_index + right, y)
                        po3.po3Labels.get(i).set_text(str.tostring(y, format.mintick))

                else

                    if na(po3.po3Labels.get(i))

                        po3.po3Labels.push(label.new(bar_index + middle, y, 
                                                 text      = pct.secondsToTfString(timeframe.in_seconds(tf)),
                                                 color     = #00000000, 
                                                 style     = label.style_label_down, 
                                                 textcolor = color.new(chart.fg_color, 25),
                                                 size      = size.tiny
                                                 ))

                    else 

                        po3.po3Labels.get(i).set_xy(bar_index + right, y)
                        po3.po3Labels.get(i).set_text(pct.secondsToTfString(timeframe.in_seconds(tf)))
 

// @function used to execute the Silver Bullet Strategy 
// @param simple bool silverBulletStratLong  input.bool() allowing the user to enable the long Silver Bullet Strategy
// @param simple bool silverBulletStratShort input.bool() allowing the user to enable the short Silver Bullet Strategy
// @param future a future time, used for drawings, example "last_bar_time"
// @param simple int userTF  user-selected timeframe the strategy should calculate on
// @param H the high price of the user-selected TF
// @param L the low price of the user-selected TF
// @param H2 the high[2] price of the user-selected TF
// @param L2 the low[2] price of the user-selected TF
// @param noBorders an input.bool() used to remove the borders from box drawings
// @param silverBulletLevels silverBulletLongTP an enum used to determine the TP used for the silver bullet long strategy - example below
// @param array<chart.point> historicalPoints an array of historical chart points corresponding to swing highs and swing lows
// @param necessaryData historicalData the UDT "necessaryData" as defined above. Contains array sof historical price points and other data
// @param silverBulletLevels silverBulletLongSL  an enum used to determine the SL used for the silver bullet long strategy - example below
// @param silverBulletLevels silverBulletShortTP an enum used to determine the TP used for the silver bullet short strategy - example below
// @param silverBulletLevels silverBulletShortSL an enum used to determine the SL used for the silver bullet short strategy - example below
// @exampleInputs
	// silverBulletStratLong    = input.bool(defval = false, title = "Silver Bullet Strategy Long", group = "Silver Bullet")
	// silverBulletLongTP       = input.enum(defval = IQ.silverBulletLevels.sH, title = "Silver Bullet Long Strategy TP", options = [IQ.silverBulletLevels.pdH, IQ.silverBulletLevels.sH], group = "Silver Bullet")
	// silverBulletLongSL       = input.enum(defval = IQ.silverBulletLevels.sL, title = "Silver Bullet Long Strategy SL", options = [IQ.silverBulletLevels.pdL, IQ.silverBulletLevels.sL], group = "Silver Bullet")
	// silverBulletStratShort   = input.bool(defval = false, title = "Silver Bullet Strategy Short", group = "Silver Bullet")
	// silverBulletShortTP      = input.enum(defval = IQ.silverBulletLevels.sL, title = "Silver Bullet Short Strategy TP", options = [IQ.silverBulletLevels.pdL, IQ.silverBulletLevels.sL], group = "Silver Bullet")
	// silverBulletShortSL      = input.enum(defval = IQ.silverBulletLevels.sH, title = "Silver Bullet Short Strategy SL", options = [IQ.silverBulletLevels.pdH, IQ.silverBulletLevels.sH], group = "Silver Bullet")
// @returns void	 

export silverBullet(simple bool silverBulletStratLong, simple bool silverBulletStratShort, int future, simple int userTF, 
     float H, float L, float H2, float L2, bool noBorders, silverBulletLevels silverBulletLongTP, 
         array<chart.point> historicalPoints, necessaryData historicalData, silverBulletLevels silverBulletLongSL, 
             silverBulletLevels silverBulletShortTP, silverBulletLevels silverBulletShortSL) =>


    if silverBulletStratLong or silverBulletStratShort
        if timeframe.in_seconds("") > timeframe.in_seconds("5")
            var tab = table.new(position.middle_center, 99, 99, na)

            tab.cell(0, 0, "Please Use 5-Minute Timeframe Or Lower For Silver Bullet", text_color = chart.fg_color, text_size = size.huge)

        else 

            var bias = ""

            HTFdirection = IQZZ(2, "15")

            var sbDrawings = silverBulletDrawings.new()

            var array<silverBullet> sessionsTrailing = na

            sessionsArr = array.from(silverBullet.new(quickTime("0300-0400"), "London Open\n3:00 - 4:00"),
                                     silverBullet.new(quickTime("1000-1100"), "NYAM\n10:00 - 11:00"),
                                     silverBullet.new(quickTime("1400-1500"), "NYPM\n14:00 - 15:00")
                                     )

            var sessionValues                      = array.new<silverBullet>()
            var silverBulletDrawings drawingsCopy  = na

            isActive = false 

            openTrades = strategy.opentrades - 1, closedTrades = strategy.closedtrades - 1

            if strategy.opentrades > 0 or not sessionsArr.first().session and not sessionsArr.get(1).session and not sessionsArr.last().session
                strategy.cancel("Long Silver Bullet")
                strategy.cancel("Short Silver Bullet")

            if sessionValues.size() > 0

                last = sessionValues.last()

                if not na(last.sessionFVGdraw)

                    last.sessionFVGdraw.set_right(future)

                if  str.contains(strategy.opentrades.entry_id    (openTrades), "Silver Bullet") 
                         and strategy.opentrades.entry_bar_index  (openTrades)   == bar_index 

                 or str.contains(strategy.closedtrades.entry_id(closedTrades), "Silver Bullet") 
                         and strategy.closedtrades.entry_bar_index(closedTrades) == bar_index

                    last.traded := true 
                    last.sessionFVGdraw := box(na)

                    drawingsCopy := silverBulletDrawings.new(sbDrawings.tpLine.copy(), sbDrawings.tpLabel.copy(), 
                                                             sbDrawings.slLine.copy(), sbDrawings.slLabel.copy())

                    sbDrawings.tpLine .delete()
                    sbDrawings.tpLabel.delete()
                    sbDrawings.slLine .delete()
                    sbDrawings.slLabel.delete()

            if not na(drawingsCopy)

                if not na(drawingsCopy.tpLine)

                    drawingsCopy.tpLine .set_x2(future)
                    drawingsCopy.tpLabel.set_x (future)
                    drawingsCopy.slLine .set_x2(future)
                    drawingsCopy.slLabel.set_x (future)

                    if strategy.closedtrades.exit_bar_index(closedTrades) == bar_index 

                        if strategy.closedtrades.entry_id(closedTrades) == "Long Silver Bullet"

                            switch strategy.closedtrades.exit_price(closedTrades) >= strategy.closedtrades.entry_price(closedTrades)

                                true => 
                                         drawingsCopy.tpLine  := line (na),
                                         drawingsCopy.tpLabel := label(na),

                                         drawingsCopy.slLine .delete(),
                                         drawingsCopy.slLabel.delete()

                                =>
                                         drawingsCopy.slLine  := line (na),
                                         drawingsCopy.slLabel := label(na),

                                         drawingsCopy.tpLine .delete(),
                                         drawingsCopy.tpLabel.delete()

                        else 

                            switch strategy.closedtrades.exit_price(closedTrades) <= strategy.closedtrades.entry_price(closedTrades)

                                true => 
                                         drawingsCopy.tpLine  := line (na),
                                         drawingsCopy.tpLabel := label(na),

                                         drawingsCopy.slLine .delete(),
                                         drawingsCopy.slLabel.delete()

                                =>
                                         drawingsCopy.slLine  := line (na),
                                         drawingsCopy.slLabel := label(na),

                                         drawingsCopy.tpLine .delete(),
                                         drawingsCopy.tpLabel.delete()


            if silverBulletStratLong or silverBulletStratShort
                if not na(sessionsTrailing) and barstate.isconfirmed and isLastBar(userTF)

                    for [i, data] in sessionsArr 

                        if data.session 

                            isActive := true 

                            if not sessionsTrailing.get(i).session

                                if sessionValues.size() > 0
                                    sessionValues.last().sessionFVGdraw.delete()
                                sessionValues.clear()

                                bias := switch HTFdirection

                                    1  => "Bullish"
                                    -1 => "Bearish"

                                sessionValues.push(

                                     silverBullet.new(data.session, data.sessionStr, bias, 

                                         sessionDraw = 
                                                         box.new(time, high, future, low, 
                                                                         bgcolor      = color.new(chart.fg_color, 95),
                                                                         border_color = chart.fg_color,
                                                                         xloc         = xloc.bar_time,
                                                                         border_style = line.style_dashed             
                                                             ),


                                         sessionDrawLabel = label.new(time, high, color = #00000000, textcolor = chart.fg_color,
                                                                         xloc         = xloc.bar_time,
                                                                         text         = data.sessionStr, 
                                                                         size         = size.small
                                                                         )))


                            else if sessionValues.size() > 0

                                getSessionValues = sessionValues.last()
                                getSessionValues.sessionHigh := math.max(H, getSessionValues.sessionHigh)
                                getSessionValues.sessionLow  := math.min(L, getSessionValues.sessionLow)

                                getSessionValues.sessionDraw.set_top(getSessionValues.sessionHigh)
                                getSessionValues.sessionDraw.set_rightbottom(future, getSessionValues.sessionLow )

                                getSessionValues.sessionDrawLabel.set_xy(math.round(math.avg(
                                                             getSessionValues.sessionDraw.get_left (), 
                                                             getSessionValues.sessionDraw.get_right())),
                                                             getSessionValues.sessionHigh
                                                             )



                                if bias == "Bullish" and strategy.opentrades == 0 and not getSessionValues.traded and silverBulletStratLong

                                    if H2 < L 

                                        getSessionValues.sessionFVG      := L 
                                        getSessionValues.sessionFVGdraw.delete()

                                        var borderTransp = switch noBorders
                                        
                                            true => 100 
                                            =>      25

                                        getSessionValues.sessionFVGdraw :=  box.new(

                                             time, L, future, H2, border_color = color.new(#74ffbc, borderTransp), 
                                                                 bgcolor       = color.new(#74ffbc, 95),
                                                                 xloc          = xloc.bar_time, 
                                                                 text          = "FVG", 
                                                                 text_size     = size.small, 
                                                                 text_halign   = text.align_left,
                                                                 text_color    = chart.fg_color
                                                 )

                                        tp     = float(na), sl     = float(na)
                                        tpTime = int(na)  , slTime = int(na)

                                        if silverBulletLongTP == silverBulletLevels.sH

                                            if historicalPoints.size() > 0 

                                                for dataPoints in historicalPoints

                                                    if dataPoints.price > H 

                                                        tp     := dataPoints.price 
                                                        tpTime := dataPoints.time

                                                        break 

                                        else 

                                            [dayHigh, dayHigh1] = request.security("", "1D", [high, high[1]], lookahead = barmerge.lookahead_on)

                                            tp := switch 

                                                dayHigh1 > L => dayHigh1 
                                                =>              dayHigh

                                            for [x, highs] in historicalData.highArr

                                                if highs == tp 

                                                    tpTime := historicalData.timeArr.get(x)
                                                    break

                                        if silverBulletLongSL == silverBulletLevels.sL 

                                            if historicalPoints.size() > 0 

                                                for dataPoints in historicalPoints

                                                    if dataPoints.price < L 

                                                        sl     := dataPoints.price 
                                                        slTime := dataPoints.time
                                                        break 

                                        else 

                                            [dayLow, dayLow1] = request.security("", "1D", [low, low[1]], lookahead = barmerge.lookahead_on)

                                            sl := switch 

                                                dayLow1 < L => dayLow1 
                                                =>             dayLow


                                            for [x, lows] in historicalData.lowArr

                                                if lows == sl 

                                                    slTime := historicalData.timeArr.get(x)
                                                    break


                                        if not na(tp) and not na(sl) and close > L

                                            sbDrawings.tpLine .delete()
                                            sbDrawings.tpLabel.delete()

                                            sbDrawings.tpLine := line.new(tpTime, tp, future, tp,
                                                                                 xloc  = xloc.bar_time, 
                                                                                 color = #74ffbc, 
                                                                                 style = line.style_dotted
                                                                                 )

                                            sbDrawings.tpLabel := label.new(future, tp, text = "Silver Bullet TP\n" + str.tostring(silverBulletLongTP),
                                                                                 size       = size.small, 
                                                                                 style      = label.style_label_lower_right,
                                                                                 color      = #00000000,
                                                                                 textcolor  = #74ffbc, 
                                                                                 xloc       = xloc.bar_time
                                                                                 )

                                            sbDrawings.slLine .delete()
                                            sbDrawings.slLabel.delete()

                                            sbDrawings.slLine := line.new(slTime, sl, future, sl,
                                                                                 xloc  = xloc.bar_time, 
                                                                                 color = color.rgb(255, 116, 116), 
                                                                                 style = line.style_dotted
                                                                                 )

                                            sbDrawings.slLabel := label.new(future, sl, text = "Silver Bullet SL\n" + str.tostring(silverBulletLongSL),
                                                                                 size       = size.small, 
                                                                                 style      = label.style_label_upper_right,
                                                                                 color      = #00000000,
                                                                                 textcolor  = color.rgb(255, 116, 116),
                                                                                 xloc       = xloc.bar_time
                                                                                 )


                                            strategy.entry("Long Silver Bullet", strategy.long, limit = L)
                                            strategy.exit ("Long Silver Bullet Exit", "Long Silver Bullet", limit = tp, stop = sl)


                                    if not na(getSessionValues.sessionFVGdraw)

                                        getSessionValues.sessionFVGdraw.set_right(future)

                                    continue


                                if bias == "Bearish" and strategy.opentrades == 0 and not getSessionValues.traded and silverBulletStratShort

                                    if L2 > H 

                                        getSessionValues.sessionFVG      := H 
                                        getSessionValues.sessionFVGdraw.delete()

                                        var borderTransp = switch noBorders

                                            true => 100 
                                            =>      25

                                        getSessionValues.sessionFVGdraw :=  box.new(

                                             time, H, future, L2, border_color = color.new(color.red, borderTransp), 
                                                                 bgcolor       = color.new(color.red, 95),
                                                                 xloc          = xloc.bar_time, 
                                                                 text          = "FVG", 
                                                                 text_size     = size.small, 
                                                                 text_halign   = text.align_left,
                                                                 text_color    = chart.fg_color
                                                 )

                                        tp     = float(na), sl     = float(na)
                                        tpTime = int(na)  , slTime = int(na)

                                        if silverBulletShortTP == silverBulletLevels.sL

                                            if historicalPoints.size() > 0 

                                                for dataPoints in historicalPoints

                                                    if dataPoints.price < L

                                                        tp     := dataPoints.price 
                                                        tpTime := dataPoints.time

                                                        break 

                                        else 

                                            [dayLow, dayLow1] = request.security("", "1D", [low, low[1]], lookahead = barmerge.lookahead_on)

                                            tp := switch 

                                                dayLow1 < H =>  dayLow1 
                                                =>              dayLow

                                            for [x, lows] in historicalData.lowArr

                                                if lows == tp 

                                                    tpTime := historicalData.timeArr.get(x)
                                                    break

                                        if silverBulletLongSL == silverBulletLevels.sH 

                                            if historicalPoints.size() > 0 

                                                for dataPoints in historicalPoints

                                                    if dataPoints.price > H 

                                                        sl     := dataPoints.price 
                                                        slTime := dataPoints.time
                                                        label.new(slTime, sl, xloc = xloc.bar_time)
                                                        break 

                                        else 

                                            [dayHigh, dayHigh1] = request.security("", "1D", [high, high[1]], lookahead = barmerge.lookahead_on)

                                            sl := switch 

                                                dayHigh1 > H => dayHigh1 
                                                =>              dayHigh

                                            for [x, highs] in historicalData.highArr

                                                if highs == sl 

                                                    slTime := historicalData.timeArr.get(x)
                                                    break


                                        if not na(tp) and not na(sl) and close < H

                                            sbDrawings.tpLine .delete()
                                            sbDrawings.tpLabel.delete()

                                            sbDrawings.tpLine := line.new(tpTime, tp, future, tp,
                                                                                 xloc  = xloc.bar_time, 
                                                                                 color = #74ffbc, 
                                                                                 style = line.style_dotted
                                                                                 )

                                            sbDrawings.tpLabel := label.new(future, tp, text = "Silver Bullet TP\n" + str.tostring(silverBulletShortTP),
                                                                                 size       = size.small, 
                                                                                 style      = label.style_label_upper_right,
                                                                                 color      = #00000000,
                                                                                 textcolor  = #74ffbc, 
                                                                                 xloc       = xloc.bar_time
                                                                                 )

                                            sbDrawings.slLine .delete()
                                            sbDrawings.slLabel.delete()

                                            sbDrawings.slLine := line.new(slTime, sl, future, sl,
                                                                                 xloc  = xloc.bar_time, 
                                                                                 color = color.rgb(255, 116, 116), 
                                                                                 style = line.style_dotted
                                                                                 )

                                            sbDrawings.slLabel := label.new(future, sl, text = "Silver Bullet SL\n" + str.tostring(silverBulletShortSL),
                                                                                 size       = size.small, 
                                                                                 style      = label.style_label_lower_right,
                                                                                 color      = #00000000,
                                                                                 textcolor  = color.rgb(255, 116, 116),
                                                                                 xloc       = xloc.bar_time
                                                                                 )


                                            strategy.entry("Short Silver Bullet", strategy.short, limit = H)
                                            strategy.exit ("Short Silver Bullet Exit", "Short Silver Bullet", limit = tp, stop = sl)

                                    if not na(getSessionValues.sessionFVGdraw)

                                        getSessionValues.sessionFVGdraw.set_right(future)



                sessionsTrailing := sessionsArr.copy()

    0

// @function check if existing FVGs are still valid
// @param fvgArr an array declared using the UDT FVG that contains FVG related data
// @param upFVGpricesSorted an array of bullish FVG prices, used to selective search through FVG array to remove invalidated levels
// @param dnFVGpricesSorted an array of bearish FVG prices, used to selective search through FVG array to remove invalidated levels
// @returns void (0)

export method invalidFVGcheck(array<FVG> FVGarr, array<float> upFVGpricesSorted, array<float> dnFVGpricesSorted) =>


    getMax = upFVGpricesSorted.max()
    getMin = dnFVGpricesSorted.min()

    isHigher = close < getMax 
    isLower  = close > getMin 

    if FVGarr.size() > 0
        if isHigher or isLower
        
            for i = FVGarr.size() - 1 to 0 
    
                data = FVGarr.get(i)
    
                if isHigher
                
                    if data.direction == "Up"
                    
                        if close < data.H
                        
                            if not na(data.fvgBox)
                            
                                data.fvgBox.delete()
        
                            FVGarr.remove(i)
                            
                        continue
    
                if isLower
                
                    if data.direction == "Down"
                    
                        if close > data.L
                        
                            if not na(data.fvgBox)
                            
                                data.fvgBox.delete()
    
                            FVGarr.remove(i)
    
        if isHigher
        
            getIndex = upFVGpricesSorted.binary_search_rightmost(close)
            slice    = upFVGpricesSorted.slice(math.min(getIndex, upFVGpricesSorted.size() - 1), upFVGpricesSorted.size())
    
            slice.clear()
    
        if isLower 
        
            getIndex = dnFVGpricesSorted.binary_search_rightmost(close)
            slice    = dnFVGpricesSorted.slice(0, getIndex)
            
            slice.clear()

    0



// @function draws FVGs on last bar
// @param counter a counter, as map<string, int>, keeping count of the number of FVGs drawn, makes sure that there aren't more FVGs drawn
// than int FVGshow 
// @param FVGshow the number of FVGs to show. There should be a bullish FVG show and bearish FVG show. This function "drawFVG" is used separately 
// for bearish FVG and bullish FVG. 
// @param FVGname the name of the FVG, "FVG Up" or "FVG Down" 
// @param FVGcol desired FVG color 
// @param masterCoords a map<string, float> containing the names and price points of key levels. Used to define price ranges.
// @param labelLevels an input.string with options "Inside", "Outside", "Remove". Determines whether FVG labels should be inside box, outside,
// or na. 
// @param borderTranspbox border transparency, only applicable to lite mode. 
// @param lite modetrue = no neon effect, false = neon effect 
// @param rightCoordinate the right coordinate of any drawings. Must be a time point.
// @returns void 


export method drawFVG(map<string, int> counter, int FVGshow, string FVGname, color FVGcol, FVG data, map<string, float> masterCoords, 
     string labelLevels, int borderTransp, bool liteMode, int rightCoordinate) => 

    count = counter.get(FVGname)

    if count < FVGshow
    
        if na(masterCoords.get(FVGname)) and FVGshow != 0
        
            masterCoords.put(FVGname, math.avg(data.H, data.L))

        // startTime1 = historicalData.highArr.getTime(data.H, historicalData.timeArr)
        // startTime2 = historicalData.lowArr .getTime(data.L, historicalData.timeArr)

        txt = switch labelLevels == "Inside"

            true => "FVG" 
            =>      "" 

        [bordCol, bgCol] = switch count == 0 

            true => [#00000000, #00000000]
            =>      [color.new(FVGcol, borderTransp), color.new(FVGcol, 75)]

        if count == 0 and liteMode

            bordCol := color.new(FVGcol, borderTransp)
            bgCol   := color.new(FVGcol, 75)

        data.fvgBox := box.new(data.T, data.H, rightCoordinate, data.L, 
                                 bgcolor      = bgCol,
                                 border_color = bordCol,
                                 xloc         = xloc.bar_time,
                                 text         = txt, 
                                 text_halign  = text.align_right,
                                 text_color   = color.new(chart.fg_color, 25))

        if labelLevels == "Outside"

            data.fvgLabel := label.new(rightCoordinate, math.avg(data.H, data.L),
                                     color        = #00000000,
                                     textcolor    = FVGcol,
                                     xloc         = xloc.bar_time,
                                     text         = "FVG", 
                                     style        = label.style_label_left, 
                                     size         = size.tiny
                                     )


        if count == 0 and not liteMode

            var gradientBoxes = array.new<box>(20)

            gradientBoxes.gradBoxes(FVGcol, data.T, data.L, data.H, rightCoordinate)

        counter.put(FVGname, counter.get(FVGname) + 1)

// @function check if existing order blocks are still valid
// @param bullishOBbox an array declared using the UDT orderBlock that contains bullish order block related data
// @param bearishOBbox an array declared using the UDT orderBlock that contains bearish order block related data
// @returns void (0)

export invalidBlockCheck(array<orderBlock> bullishOBbox, array<orderBlock> bearishOBbox, int userTF) => 



    if bullishOBbox.size() > 0 and barstate.isconfirmed and isLastBar(userTF)
        for i = bullishOBbox.size() - 1 to 0 

            getOrderBlock = bullishOBbox.get(i)
            getTop        = getOrderBlock.orderBlockData.get(1)
            getBot        = getOrderBlock.orderBlockData.last ()

            if getOrderBlock.vioCount == 0

                if close < getBot

                    getOrderBlock.vioCount += 1
                    getOrderBlock.status := "BB"
                    
            else 

                if close > getTop

                    bullishOBbox.remove(i).orderBlockBox.delete()

    if bearishOBbox.size() > 0 and barstate.isconfirmed and isLastBar(userTF)
        for i = bearishOBbox.size() - 1 to 0 
        
            getOrderBlock = bearishOBbox.get(i)
            getBot        = getOrderBlock.orderBlockData.last()
            getTop        = getOrderBlock.orderBlockData.get(1)

            if getOrderBlock.vioCount == 0

                if close > getTop

                    getOrderBlock.vioCount += 1    
                    getOrderBlock.status := "BB"

            else 

                if close < getBot
                    bearishOBbox.remove(i).orderBlockBox.delete()

    0


// @function draws rejectionBlocks on last bar
// @param id the array<rejectionBlocks>, an array of rejection block data declared using the UDT rejection block
// @param rejectionColor the desired color of the rejection box
// @param rejectionString the desired name of the rejection blocks
// @param labelLevels an input.string() to determine if labels for the block should be inside the box, outside, or none.
// @param borderTranspbox border transparency
// @param liteMode an input.bool(). True = neon effect, false = no neon.
// @param rightCoordinate  atime for the right coordinate of the box 
// @param masterCoords a map <string, float> that stores the price of key levels and assigns them a name, used to determine price ranges
// @returns void 


export method lastBarRejections(array<rejectionBlocks> id, color rejectionColor, int idShow, string rejectionString, string labelLevels, 
     int borderTransp, bool liteMode, int rightCoordinate, map<string, float> masterCoords) =>

    if barstate.islast 
    
        if id.size() > 0 

            countRB = 0

            txt = switch labelLevels == "Inside"

                true => "RB"
                =>      ""

            [bordCol, bgCol] = switch countRB == 0

                true => [#00000000, #00000000]
                =>      [color.new(rejectionColor, borderTransp), color.new(rejectionColor, 75)]

            if countRB == 0 and liteMode

                bordCol := color.new(rejectionColor, borderTransp)
                bgCol   := color.new(rejectionColor, 75)
            
            for [i, data] in id

                data.rejectionBox  .delete()

                if labelLevels == "Outside"

                    data.rejectionLabel.delete()

                if countRB < idShow

                    data.rejectionBox := box.new(data.rejectionPoint.time, data.rejectionPoint.price, rightCoordinate, data.bodyPrice, 
                                                 xloc         = xloc.bar_time,
                                                 bgcolor      = bgCol, 
                                                 border_color = bordCol,
                                                 text         = txt,
                                                 text_color   = color.new(chart.fg_color, 25), 
                                                 text_halign  = text.align_right
                                                 )

                    avg = math.avg(data.rejectionPoint.price, data.bodyPrice)

                    if labelLevels == "Outside"

                        data.rejectionLabel := label.new(rightCoordinate, avg, xloc = xloc.bar_time, 
                                                             size      = size.tiny, 
                                                             text      = "RB", 
                                                             color     = #00000000, 
                                                             style     = label.style_label_left, 
                                                             textcolor = rejectionColor
                                                                 )

                    if countRB == 0 and not liteMode

                        masterCoords.put(rejectionString, data.rejectionPoint.price)

                        bottom = data.bodyPrice, top = data.rejectionPoint.price

                        var gradientBoxes = array.new<box>(20)

                        gradientBoxes.gradBoxes(rejectionColor, data.rejectionPoint.time, bottom, top, rightCoordinate)

                    countRB += 1



// @function draws orderblocks and breaker blocks for data stored in UDT array<orderBlock>() 
// @param id the array<orderBlock>, an array of order block data declared using the UDT orderblock 
// @param OBshow the number of order blocks to show
// @param BBshow the number of breaker blocks to show
// @param OBcol color of order blocks
// @param BBcol color of breaker blocks
// @param bullishString the title of bullish blocks, which is a regular bullish orderblock or a bearish orderblock that's converted to breakerblock 
// @param bearishString the title of bearish blocks, which is a regular bearish orderblock or a bullish orderblock that's converted to breakerblock 
// @param isBullish whether the array<orderBlock> contains bullish orderblocks or bearish orderblocks. If bullish orderblocks, 
// the array will naturally contain bearish BB, and if bearish OB, the array will naturally contain bullish BB
// @param labelLevels an input.string() to determine if labels for the block should be inside the box, outside, or none.
// @param borderTranspbox border transparency
// @param liteMode an input.bool(). True = neon effect, false = no neon.
// @param rightCoordinate  atime for the right coordinate of the box 
// @param masterCoords a map <string, float> that stores the price of key levels and assigns them a name, used to determine price ranges
// @returns void 


export method OBdraw(array<orderBlock> id, int OBshow, int BBshow, color OBcol, color BBcol, string bullishString, string bearishString, bool isBullish,
     string labelLevels, int borderTransp, bool liteMode, int rightCoordinate, map<string, float> masterCoords) =>

    if barstate.islast

        countOB = 0, countBB = 0
    
        if id.size() > 0
            for i = 0 to id.size() - 1
    
                getData = id.get(i)
    
                getData.orderBlockBox.delete()
    
                if labelLevels == "Outside"
                
                    getData.orderBlockLab.delete()
    
                if countOB < OBshow
                    
                    if getData.status == "OB"
                    
                        halign = text.align_right
    
                        txt = switch labelLevels == "Inside"
                        
                            true => "OB"
                            =>      ""
    
                        [bordCol, bgCol] = switch countOB == 0
                        
                            true => [#00000000, #00000000]
                            =>      [color.new(OBcol, borderTransp), color.new(OBcol, 75)]
    
                        if countOB == 0 and liteMode
                        
                            bordCol := color.new(OBcol, borderTransp)
                            bgCol   := color.new(OBcol, 75)
                        
                        getData.orderBlockBox := box.new(
                             int(getData.orderBlockData.first()), getData.orderBlockData.get(1), 
                             rightCoordinate, getData.orderBlockData.last(), 
                             border_color = bordCol,
                             bgcolor      = bgCol,
                             xloc         = xloc.bar_time,
                             border_style = line.style_solid, 
                             text         = txt,
                             text_halign  = halign,
                             text_color   = color.new(chart.fg_color, 25)
                         )
    
                        if labelLevels == "Outside"
                        
                            getData.orderBlockLab := label.new(rightCoordinate, math.avg(getData.orderBlockData.get(1), getData.orderBlockData.last()), 
                                                                     color     = #00000000, 
                                                                     textcolor = OBcol, 
                                                                     text      = "OB", 
                                                                     style     = label.style_label_left, 
                                                                     xloc      = xloc.bar_time, 
                                                                     size      = size.tiny 
                                                                     )
    
                        if countOB == 0 and not liteMode
                        
                            bottom = getData.orderBlockData.last(), top = getData.orderBlockData.get(1)
    
                            avg = math.avg(top, bottom)
    
                            var gradientBoxes = array.new<box>(20)
    
                            gradientBoxes.gradBoxes(OBcol, int(getData.orderBlockData.first()), bottom, top, rightCoordinate)
                            
    
                        countOB += 1
    
                        str = switch isBullish 
                        
                            true => bullishString 
                            =>      bearishString
    
                        if na(masterCoords.get(str)) and OBshow != 0
                        
                            masterCoords.put(str, math.avg(getData.orderBlockBox.get_top(), getData.orderBlockBox.get_bottom()))
    
                if countBB < BBshow
                
                    if getData.status == "BB"
                    
                        halign = text.align_right
    
                        txt = switch labelLevels == "Inside"
                        
                            true => "BB"
                            =>      ""
    
                        [bordCol, bgCol] = switch countBB == 0
                        
                            true => [#00000000, #00000000]
                            =>      [color.new(BBcol, borderTransp), color.new(BBcol, 75)]
    
                        if countBB == 0 and liteMode
                        
                            bordCol := color.new(BBcol, borderTransp)
                            bgCol   := color.new(BBcol, 75)
    
    
                        getData.orderBlockBox := box.new(
                             int(getData.orderBlockData.first()), getData.orderBlockData.get(1), 
                             rightCoordinate, getData.orderBlockData.last(), 
                             border_color = bordCol,
                             bgcolor      = bgCol,
                             xloc         = xloc.bar_time,
                             border_style = line.style_solid,
                             text         = txt,
                             text_halign  = halign,
                             text_color   = color.new(chart.fg_color, 25)
                         )
                         
    
                        if labelLevels == "Outside"
                        
                            getData.orderBlockLab := label.new(rightCoordinate, math.avg(getData.orderBlockData.get(1), getData.orderBlockData.last()), 
                                                                     color     = #00000000, 
                                                                     textcolor = BBcol, 
                                                                     text      = "BB", 
                                                                     style     = label.style_label_left, 
                                                                     xloc      = xloc.bar_time, 
                                                                     size      = size.tiny 
                                                                     )
    
    
                        if countBB == 0 and not liteMode
                        
                            bottom = getData.orderBlockData.last(), top = getData.orderBlockData.get(1)
                            
                            var gradientBoxes = array.new<box>(20)
    
                            gradientBoxes.gradBoxes(BBcol, int(getData.orderBlockData.first()), bottom, top, rightCoordinate)
    
    
                        countBB += 1
    
                        str = switch isBullish 
                        
                            true => bearishString 
                            =>      bullishString
    
                        if na(masterCoords.get(str)) and BBshow != 0
                        
                            masterCoords.put(str, math.avg(getData.orderBlockBox.get_top(), getData.orderBlockBox.get_bottom()))

